### ISSUE TITLE
Again AUR down!

### ISSUE THREAD

**Issue by shawanroy** [mnixry/mixout-aur#1] opened 2022-06-17 16:07 UTC
The AUR link already down.
URL: https://aur.archlinux.org/packages/tabby-terminal

**Comment by mnixry** [comment] 2022-06-18 10:12
Thank you for feedback to this package. It has been merged into `tabby-bin` :cry: 

Seems like AUR community don't like use `tabby-terminal` as package name. This is the second time it happened.

I will try to submit an orphan request to maintain `tabby-bin` package, since `tabby-terminal` can't be accepted by the community.

I'm sorry for any inconvenience caused by this change.

**Comment by shawanroy** [comment] 2022-06-21 15:42
Though the AUR repo is not fixed, I already update through makepkg -si command and works perfectly.

**Comment by mnixry** [comment] 2022-06-22 02:22
Thanks to @SolarAquarion for adding me as co-maintainer, I'm now able to maintain package `tabby`.

I've migrated scripts from `tabby-terminal` to `tabby`, so you can get latest release from `tabby` package.

---

Since this issue is basically solved, I will close this issue as completed. If you have issues related to this, please feel free to reopen this issue or create a new issue.

**Closed as completed by mnixry** 2022-06-22 02:22 UTC

**Comment by SolarAquarion** [comment] 2022-06-22 03:00
the issue is that tabby is from source, not a binary
